(require "asdf")

(defun day1-parse (file)
  (loop for line in (uiop:read-file-lines file)
	collect (list (char line 0) (parse-integer line :start 1))))

(defun day1-1 (file) 
  (let ((value 50) (0-count 0))
    (dolist (elem (day1-parse file))
      (incf value (case (first elem)
		    (#\R (second elem))
		    (#\L (- (second elem)))
		    (t 0)))
      (setf value (mod value 100))
      (when (= value 0) (incf 0-count)))
    (format t "~a~%" 0-count)))

(defun day1-2 (file) 
  (let ((value 50) (0-count 0))
    (dolist (elem (day1-parse file))
      ;; Yes it's awful, but it works
      (case (first elem)
	(#\L (dotimes (i (second elem))
	       (setf value (mod (1- value) 100))
	       (when (= value 0) (incf 0-count))))
	(#\R (dotimes (i (second elem))
	       (setf value (mod (1+ value) 100))
	       (when (= value 0) (incf 0-count))))
	(t nil)))
    (format t "~a~%" 0-count)))  
