(require "asdf")

(defun day4-parse (file)
  (loop for line in (uiop:read-file-lines file)
	collect (loop for c across line collect c)))

(defun get-2d (list row col &key default)
  (let ((n-row (nth row list)))
    (or (and n-row (nth col n-row))
	default)))

(defun shift-down (grid)
  (cons (make-list (length (car grid)) :initial-element #\.) (copy-tree grid)))

(defun shift-up (grid)
  (append (cdr grid) (list (make-list (length (car grid)) :initial-element #\.))))

(defun shift-right (grid)
  (mapcar (lambda (l) (cons #\. l)) grid))

(defun shift-left (grid)
  (mapcar (lambda (l) (append (cdr l) (list #\.))) grid))

(defun day4-1 (file)
  (let ((grid (day4-parse file))
	(count 0))
    (let ((tl (shift-down (shift-right grid)))
	  (tc (shift-down grid))
	  (tr (shift-down (shift-left grid)))
	  (cl (shift-right grid))
	  (cc grid)
	  (cr (shift-left grid))
	  (bl (shift-up (shift-right grid)))
	  (bc (shift-up grid))
	  (br (shift-up (shift-left grid))))
      (mapcar (lambda (&rest rows)
		(apply #'mapcar
		       (lambda (&rest elems)
			 (when (and (eql #\@ (nth 4 elems))
				    (> 5 (count-if (lambda (c) (eql c #\@)) elems)))
			   (incf count)))
		       rows))
	      tl tc tr cl cc cr bl bc br))
    count))

(defun day4-step (grid)
  (let ((tl (shift-down (shift-right grid)))
	(tc (shift-down grid))
	(tr (shift-down (shift-left grid)))
	(cl (shift-right grid))
	(cc grid)
	(cr (shift-left grid))
	(bl (shift-up (shift-right grid)))
	(bc (shift-up grid))
	(br (shift-up (shift-left grid)))
	(count 0))
    (list
     (mapcar (lambda (&rest rows)
	       (apply #'mapcar
		      (lambda (&rest elems)
			(if (and (char= #\@ (nth 4 elems))
				 (> 5 (count-if (lambda (c) (char= c #\@)) elems)))
			    (progn (incf count)
				   #\.)
			    (nth 4 elems)))
		      rows))
	     tl tc tr cl cc cr bl bc br)
     count)
    ))

(defun day4-2 (file)
  (let ((grid (day4-parse file))
	(total-count 0))
    (loop do
      (destructuring-bind (new-grid count) (day4-step grid)
	    (setf grid new-grid)
	    (when (= 0 count) (return))
	    (incf total-count count)))
    total-count))
